import ClientProviders from './client-providers';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className="bg-gray-50 min-h-screen">
        <ClientProviders>
          <main className="max-w-2xl mx-auto w-full px-2 py-6">{children}</main>
        </ClientProviders>
      </body>
    </html>
  );
}
